
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Adinda puspitasari
 */
public class perpustakaan extends javax.swing.JFrame {

    /**
     * Creates new form perpustakaan
     */
    public perpustakaan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LJudul = new javax.swing.JLabel();
        LGenre = new javax.swing.JLabel();
        LPengarang = new javax.swing.JLabel();
        LPenerbit = new javax.swing.JLabel();
        LTahun = new javax.swing.JLabel();
        eJudul = new javax.swing.JComboBox<>();
        eGenre = new javax.swing.JTextField();
        ePengarang = new javax.swing.JTextField();
        eTahun = new javax.swing.JTextField();
        bPinjam = new javax.swing.JButton();
        bKembali = new javax.swing.JButton();
        LNama = new javax.swing.JLabel();
        LNim = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        eNim = new javax.swing.JTextField();
        ePenerbit = new javax.swing.JTextField();
        eReset = new javax.swing.JButton();

        jLabel11.setText("jLabel11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(193, 91, 91));
        jPanel1.setLayout(new java.awt.BorderLayout(20, 20));

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HISTORIA LIBRARY");
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);
        jPanel1.add(jLabel3, java.awt.BorderLayout.LINE_END);
        jPanel1.add(jLabel4, java.awt.BorderLayout.PAGE_END);
        jPanel1.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        LJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LJudul.setText("Judul Buku");

        LGenre.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LGenre.setText("Genre");

        LPengarang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LPengarang.setText("Pengarang");

        LPenerbit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LPenerbit.setText("Penerbit");

        LTahun.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LTahun.setText("Tahun Terbit");

        eJudul.setEditable(true);
        eJudul.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JUDUL BUKU", "Dragon Ball", "Attack On Titan", "Haikyuu!", "One Piece", "Horimiya", "Tokyou Ghoul" }));
        eJudul.setToolTipText("");
        eJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eJudulActionPerformed(evt);
            }
        });

        bPinjam.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        bPinjam.setText("PINJAM");
        bPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPinjamActionPerformed(evt);
            }
        });

        bKembali.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        bKembali.setText("KEMBALIKAN");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        LNama.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LNama.setText("Nama");

        LNim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LNim.setText("NIM");

        eReset.setFont(new java.awt.Font("Square721 BT", 1, 12)); // NOI18N
        eReset.setText("RESET");
        eReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LJudul)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LNim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(LNama)
                                .addGap(104, 104, 104)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eNim, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LGenre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(LPengarang)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                                .addComponent(ePengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(bPinjam)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(eReset)
                                .addGap(18, 18, 18)
                                .addComponent(bKembali))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LTahun)
                                    .addComponent(LPenerbit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(eTahun)
                                    .addComponent(ePenerbit, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))))))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LNama))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(eNim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LJudul))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eGenre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LGenre))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(LNim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(96, 96, 96)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPengarang)
                    .addComponent(ePengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LPenerbit)
                    .addComponent(ePenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eTahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LTahun))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKembali)
                    .addComponent(bPinjam)
                    .addComponent(eReset))
                .addGap(18, 18, 18))
        );

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eJudulActionPerformed
        String judul = eJudul.getSelectedItem().toString();
        
        switch (judul) {
            case "Dragon Ball" -> {
                eGenre.setText("Fantasi Action");
                ePengarang.setText("Akira Toriyama");
                ePenerbit.setText("Shueisha");
                eTahun.setText("1984");
            }
            case "Attack On Titan" -> {
                eGenre.setText("Horror");
                ePengarang.setText("Hajime Isayama");
                ePenerbit.setText("Shueisha");
                eTahun.setText("2009");
            }
            case "Haikyuu!" -> {
                eGenre.setText("Sport");
                ePengarang.setText("Haruichi Furudate");
                ePenerbit.setText("Shueisha");
                eTahun.setText("2012");
            }
            case "One Piece" -> {
                eGenre.setText("Aksi");
                ePengarang.setText("Eiichiro Oda");
                ePenerbit.setText("Weekly Shonen Jump");
                eTahun.setText("1997");
            }
            case "Horimiya" -> {
                eGenre.setText("Romance");
                ePengarang.setText("Hero");
                ePenerbit.setText("Square Enix");
                eTahun.setText("2007");
            }
            case "Tokyo Ghoul" -> {
                eGenre.setText("Horror");
                ePengarang.setText("Sui Ishida");
                ePenerbit.setText("Shueisha");
                eTahun.setText("2011");
            }
        }                                
    }//GEN-LAST:event_eJudulActionPerformed

    private void bPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPinjamActionPerformed
       String nama = eNama.getText();
       String nim = eNim.getText();
       String judul = (String) eJudul.getSelectedItem();
       String genre = eGenre.getText();
       String pengarang = ePengarang.getText();
       String penerbit = ePenerbit.getText(); 
       String tahunTerbit = eTahun.getText();
    
      if (nama.isEmpty() || nim.isEmpty() || judul.isEmpty() || genre.isEmpty() ||
        pengarang.isEmpty() || penerbit.isEmpty() || tahunTerbit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi semua field terlebih dahulu.");
    } else {
        // Lanjutkan dengan tindakan peminjaman jika semua input sudah diisi
        JOptionPane.showMessageDialog(this, "TELAH MEMINJAM BUKU" + "\nNama : " + nama + "\nNIM: " 
                + nim + "\nJudul Buku: " + judul + "\nGenre: " + genre + "\nPengarang: " + pengarang + 
                "\nPenerbit: " + penerbit + "\nTahun Terbit: " + tahunTerbit);
      }
        eNama.setText("");
        eNim.setText("");
        eJudul.setSelectedIndex(0);
        eGenre.setText("");
        ePengarang.setText("");
        ePenerbit.setText("");
        eTahun.setText("");
    }//GEN-LAST:event_bPinjamActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
         String nama = eNama.getText();
       String nim = eNim.getText();
       String judul = (String) eJudul.getSelectedItem();
       String genre = eGenre.getText();
       String pengarang = ePengarang.getText();
       String penerbit = ePenerbit.getText();
       String tahunTerbit = eTahun.getText();
    
      if (nama.isEmpty() || nim.isEmpty() || judul.isEmpty() || genre.isEmpty() ||
        pengarang.isEmpty() || penerbit.isEmpty() || tahunTerbit.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harap isi semua field terlebih dahulu.");
    } else {
        // Lanjutkan dengan tindakan peminjaman jika semua input sudah diisi
        JOptionPane.showMessageDialog(this, "TELAH MENGEMBALIKAN BUKU" + "\nNama : " + nama + "\nNIM: " 
                + nim + "\nJudul Buku: " + judul + "\nGenre: " + genre + "\nPengarang: " + pengarang + 
                "\nPenerbit: " + penerbit + "\nTahun Terbit: " + tahunTerbit);
      }
        eNama.setText("");
        eNim.setText("");
        eJudul.setSelectedIndex(0);
        eGenre.setText("");
        ePengarang.setText("");
        ePenerbit.setText("");
        eTahun.setText("");
                                   
    }//GEN-LAST:event_bKembaliActionPerformed

    private void eResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eResetActionPerformed
        eNama.setText("");
        eNim.setText("");
        eJudul.setSelectedIndex(0);
        eGenre.setText("");
        ePengarang.setText("");
        ePenerbit.setText("");
        eTahun.setText("");
    }//GEN-LAST:event_eResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(perpustakaan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new perpustakaan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LGenre;
    private javax.swing.JLabel LJudul;
    private javax.swing.JLabel LNama;
    private javax.swing.JLabel LNim;
    private javax.swing.JLabel LPenerbit;
    private javax.swing.JLabel LPengarang;
    private javax.swing.JLabel LTahun;
    private javax.swing.JButton bKembali;
    private javax.swing.JButton bPinjam;
    private javax.swing.JTextField eGenre;
    private javax.swing.JComboBox<String> eJudul;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField eNim;
    private javax.swing.JTextField ePenerbit;
    private javax.swing.JTextField ePengarang;
    private javax.swing.JButton eReset;
    private javax.swing.JTextField eTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
